#!/bin/bash

EQUERY="/usr/bin/equery"
EMERGE="/usr/bin/emerge"

SLOT="7"

KDE_APPS="
x11-libs/qt
kde-base/kdelibs

kde-base/libkonq
kde-base/kcminit
kde-base/kdebase-data
kde-base/kxkb
kde-base/kdesktop
kde-base/kwin
kde-base/kicker
kde-base/kcontrol
kde-base/kdm
kde-base/kdebase-startkde
kde-base/kappfinder
kde-base/konsole
kde-base/drkonqi
kde-base/kate
kde-base/kcheckpass
kde-base/kdcop
kde-base/kdialog
kde-base/ksplashml
kde-base/kdebase-kioslaves
kde-base/kdebugdialog
kde-base/kdepasswd
kde-base/kdeprint
kde-base/kdesu
kde-base/kfind
kde-base/khelpcenter
kde-base/khotkeys
kde-base/klipper
kde-base/konqueror
kde-base/nsplugins
kde-base/kmenuedit
kde-base/kpager
kde-base/knetattach
kde-base/kreadconfig
kde-base/kpersonalizer
kde-base/kscreensaver
kde-base/ksmserver
kde-base/kstart
kde-base/ksysguard
kde-base/ksystraycmd
kde-base/ktip

kde-base/librss
kde-base/dcoprss
kde-base/kdenetwork-filesharing
kde-base/kdenetwork-kfile-plugins
kde-base/kdict
kde-base/kdnssd
kde-base/kget
kde-base/knewsticker
kde-base/kopete
kde-base/kpf
kde-base/kppp
kde-base/krdc
kde-base/krfb
kde-base/ksirc
kde-base/ktalkd
kde-base/kwifimanager
kde-base/lisa

kde-base/libkdenetwork
kde-base/libkdepim
kde-base/ktnef
kde-base/libkcal
kde-base/libkpimexchange
kde-base/libkholidays
kde-base/libkmime
kde-base/libkpgp
kde-base/certmanager
kde-base/libkpimidentities
kde-base/libksieve
kde-base/mimelib
kde-base/kdepim-kioslaves
kde-base/kontact
kde-base/networkstatus
kde-base/akregator
kde-base/kmailcvt
kde-base/korganizer
kde-base/kmail
kde-base/kode
kde-base/kdepim-kresources
kde-base/kaddressbook
kde-base/kontact-specialdates
kde-base/kdepim-wizards
kde-base/knotes
kde-base/kdgantt
kde-base/kalarm
kde-base/kandy
kde-base/karm
kde-base/kitchensync
kde-base/kmobile
kde-base/knode
kde-base/konsolekalendar
kde-base/korn
kde-base/kpilot
kde-base/ksync

kde-base/kdeadmin-kfile-plugins
kde-base/kcmlinuz
kde-base/kcron
kde-base/kdat
kde-base/kpackage
kde-base/ksysv
kde-base/kuser
kde-base/lilo-config
kde-base/secpolicy

kde-base/ark
kde-base/kcalc
kde-base/kcardtools
kde-base/kcharselect
kde-base/kdelirc
kde-base/kdf
kde-base/kedit
kde-base/kfloppy
kde-base/kgpg
kde-base/khexedit
kde-base/kjots
kde-base/klaptopdaemon
kde-base/kmilo
kde-base/kregexpeditor
kde-base/ksim
kde-base/ktimer
kde-base/kwalletmanager

media-libs/taglib
kde-base/libkcddb
kde-base/kdemultimedia-kioslaves
kde-base/kdemultimedia-kfile-plugins
kde-base/kdemultimedia-kappfinder-data
kde-base/kdemultimedia-arts
kde-base/artsplugin-audiofile
kde-base/mpeglib
kde-base/artsplugin-mpeglib
kde-base/artsplugin-mpg123
kde-base/artsplugin-xine
kde-base/akode
kde-base/juk
kde-base/kaboodle
kde-base/kaudiocreator
kde-base/kmid
kde-base/kmix
kde-base/krec
kde-base/kscd
kde-base/noatun

kde-base/kdegraphics-kfile-plugins
kde-base/libkscan
kde-base/kamera
kde-base/kcoloredit
kde-base/kviewshell
kde-base/kdvi
kde-base/kfax
kde-base/kgamma
kde-base/kghostview
kde-base/kiconedit
kde-base/kmrml
kde-base/kolourpaint
kde-base/kooka
kde-base/kpdf
kde-base/kpovmodeler
kde-base/kruler
kde-base/ksnapshot
kde-base/ksvg
kde-base/kuickshow
kde-base/kview

kde-base/kbstateapplet
kde-base/kdeaccessibility-iconthemes
kde-base/kmag
kde-base/kmousetool
kde-base/kmouth
kde-base/kttsd
kde-base/ksayit

kde-base/amor
kde-base/eyesapplet
kde-base/fifteenapplet
kde-base/kmoon
kde-base/kodo
kde-base/kteatime
kde-base/ktux
kde-base/kweather
kde-base/kworldwatch

kde-base/kfilereplace
kde-base/kimagemapeditor
kde-base/klinkstatus
kde-base/kommander
kde-base/kxsldbg
kde-base/quanta


kde-base/kdesdk-kfile-plugins
kde-base/kdesdk-kioslaves
kde-base/kdesdk-misc
kde-base/kdesdk-scripts	
kde-base/cervisia
kde-base/kapptemplate
kde-base/kbabel
kde-base/kbugbuster
kde-base/kcachegrind
kde-base/kmtrace
kde-base/kompare
kde-base/kspy
kde-base/kuiviewer
kde-base/umbrello

kde-base/libkdeedu
kde-base/kalzium
kde-base/kbruch
kde-base/keduca
kde-base/khangman
kde-base/kig
kde-base/kiten
kde-base/klatin
kde-base/klettres
kde-base/kmathtool
kde-base/kmessedwords
kde-base/kmplot
kde-base/kpercentage
kde-base/kstars
kde-base/ktouch
kde-base/kturtle
kde-base/kverbos
kde-base/kvoctrain
kde-base/kwordquiz

kde-base/libkdegames
kde-base/atlantik
kde-base/kasteroids
kde-base/katomic
kde-base/kbackgammon
kde-base/kbattleship
kde-base/kblackbox
kde-base/kbounce
kde-base/kenolaba
kde-base/libksirtet
kde-base/kfouleggs
kde-base/kgoldrunner
kde-base/kjumpingcube
kde-base/klickety
kde-base/klines
kde-base/kmahjongg
kde-base/kmines
kde-base/kolf
kde-base/konquest
kde-base/kpat
kde-base/kpoker
kde-base/kreversi
kde-base/ksame
kde-base/kshisen
kde-base/ksirtet
kde-base/ksmiletris
kde-base/ksnake
kde-base/ksokoban
kde-base/kspaceduel
kde-base/ktron
kde-base/ktuberling
kde-base/kwin4
kde-base/lskat

kde-base/atlantikdesigner
kde-base/kaddressbook-plugins
kde-base/kate-plugins
kde-base/kdeaddons-docs-konq-plugins
kde-base/kdeaddons-kfile-plugins
kde-base/kicker-applets
kde-base/knewsticker-scripts
kde-base/konq-plugins
kde-base/konqueror-akregator
kde-base/ksig
kde-base/noatun-plugins
kde-base/renamedlg-audio
kde-base/renamedlg-images
kde-base/vimpart

kde-base/dcopc
kde-base/dcopjava
kde-base/dcopperl
kde-base/dcoppython
kde-base/kalyptus
kde-base/kdejava
kde-base/kjsembed
kde-base/smoke
kde-base/qtruby
kde-base/korundum
kde-base/qtjava
kde-base/qtsharp
kde-base/xparts

kde-base/kdeartwork-emoticons
kde-base/kdeartwork-icewm-themes
kde-base/kdeartwork-iconthemes
kde-base/kdeartwork-kscreensaver
kde-base/kdeartwork-kwin-styles
kde-base/kdeartwork-kworldclock
kde-base/kdeartwork-sounds
kde-base/kdeartwork-styles
kde-base/kdeartwork-wallpapers

app-office/koffice-data
app-office/koffice-libs
app-office/karbon
app-office/kchart
app-office/kformula
app-office/kivio
app-office/koshell
app-office/kpresenter
app-office/kspread
app-office/kugar
app-office/kexi
app-office/krita
app-office/kplato
app-office/kword

app-admin/kconfigeditor
app-admin/kiosktool
app-cdr/k3b
app-editors/kile
app-editos/yzis
dev-util/kcfgcreator
dev-util/kdevelop
games-board/gamesman
kde-misc/kat
kde-misc/komose
kde-misc/pwmanager
media-libs/libkexif
media-libs/libkipi
media-gfx/digikam
media-gfx/kst
media-plugins/kipi-plugins
media-gfx/showimg
media-plugins/digikamimageplugins
media-sound/amarok
media-sound/kradio
media-tv/kdetv
media-video/kaffeine
media-video/kmplayer
media-video/kplayer
net-irc/konversation
net-p2p/apollon
net-p2p/kmldonkey
net-p2p/ktorrent
net-wireless/kdebluetooth
x11-themes/gtk-qt-engine
"

# Check if emerge command is found and executable
if [ ! -x ${EMERGE} ]; then
	die "Command not found: ${EMERGE}"
fi

# Check if equery is installed (from gentoolkit package)
if [ ! -x ${EQUERY} ]; then
	die "Command not found: ${EQUERY} ! Please install app-portage/gentoolkit"
fi

# Loop list of KDE APPS
for i in ${KDE_APPS} ; do

	if [ -n "${i}" ]; then

		# check if app exists and is installed
		#PACKAGE=`${EQUERY} list "${i}" | grep "${i}-${SLOT}" | cut -d"/" -f2`
		PACKAGE=`${EQUERY} list "${i}" | grep "${i}-${SLOT}"`
		if [ -n "${PACKAGE}" ]; then

			FEATURES="autoskipcvs" ${EMERGE} "=${i}" -v

		fi
	fi

done

echo ""
echo ">>> Done updating KDE !!!"